#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "BAD" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2JhZDQvdS9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO == "BAD" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2JhZDQvdS9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2JhZDQvdS9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="BadBot.zip"
    echo "Downloading BAD userbot source files ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "Opening source files ...​"
    BADPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "Downloading ..."
    rm -rf "$zippath"
    sleep 5
    cd $BADPATH
    echo "Start Bad userbot"
    echo "
                       
┏┓┏━┓┏┓
​┃┗┳━╋┛┃
┃┃┃┃┃┃┃
┗━┻━┻━┛ 
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
